"""Compare bias_wo (T_pi definition) between Jake's old DUNE 0.7-MFP file
(.bak.preNNmfp) and our May-1 piabs100 baseline (.bak.preOPpatch).

For each file: vertex stack (noFSI view) and post-FSI stack -> 4 lines.

If Jake's 0.7-MFP was actually generated by re-running NuWro with
kaskada_NN_mfp_scale=0.7, the FSI line will have noticeably more rescattering
(broader, peaks shifted). If it's a reweighted hack, the FSI line shape
will match the piabs100 nominal."""
from FlatTreeMod import *
import numpy as np

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

FILES = [
    ("Jake old 0p7MFP (preNNmfp)",
     "/eos/project-n/neutrino-generators/generatorOutput/FSIIOPPaperinputs/DUNE/ChangeMFP/DUNE_numu_0p7MFP_FSI.flat.root.bak.preNNmfp"),
    ("Our piabs100 nominal (preOPpatch)",
     "/eos/project-n/neutrino-generators/generatorOutput/FSIIOPPaperinputs/DUNE/piabs/DUNE_numu_piabs100_FSI.flat.root.bak.preOPpatch"),
]

bin_width = 16.0   # MeV
bins = np.arange(-1000, 1000 + bin_width, bin_width)

fig, (ax_top, ax_ratio) = plt.subplots(2, 1, sharex=True,
                                       gridspec_kw={"height_ratios": [3, 1], "hspace": 0.05},
                                       figsize=(8, 6))

palette = {
    "Jake old 0p7MFP (preNNmfp) noFSI":     ("#0077BB", "-"),   # blue
    "Jake old 0p7MFP (preNNmfp) FSI":       ("#0077BB", "--"),
    "Our piabs100 nominal (preOPpatch) noFSI": ("#CC3311", "-"),  # red
    "Our piabs100 nominal (preOPpatch) FSI":   ("#CC3311", "--"),
}

# we'll dσ/dE-style — make_weights_dxsec in MeV bin_width
counts_all = {}
for label, path in FILES:
    arr = load_arrays(path, max_events=200000)
    fScale = float(np.max(arr["fScaleFactor"]))
    for vertex_flag, tag in ((True, "noFSI"), (False, "FSI")):
        bias_wo_GeV, _, _ = enu_had_arr(arr, vertex=vertex_flag)
        bias_MeV = bias_wo_GeV * 1000.0
        w = make_weights_dxsec(arr, bin_width, fScale) * np.ones_like(bias_MeV)
        full_lbl = f"{label} {tag}"
        c, _ = np.histogram(bias_MeV, bins=bins, weights=w)
        counts_all[full_lbl] = c
        color, ls = palette[full_lbl]
        ax_top.hist(bias_MeV, bins=bins, weights=w, histtype="step",
                    color=color, lw=1.5, ls=ls, label=full_lbl)

# ratio panel: post-FSI / vertex (noFSI) for each file
for label, _ in FILES:
    nf = counts_all[f"{label} noFSI"]
    fs = counts_all[f"{label} FSI"]
    centers = 0.5 * (bins[:-1] + bins[1:])
    ratio = fs / np.maximum(nf, 1e-30)
    color, _ = palette[f"{label} noFSI"]
    ax_ratio.step(centers, ratio, where="mid", color=color, lw=1.5,
                  label=f"{label}: FSI/noFSI")

ax_top.set_xlim(-1000, 1000)
ax_top.set_ylabel(DSIGMA_DE_LABEL)
ax_top.legend(fontsize=8, loc="upper left")
ax_ratio.axhline(1, color="black", ls=":")
ax_ratio.set_xlabel(r"$E_{\nu}^{\mathrm{reco}} - E_{\nu}^{\mathrm{true}}$ [MeV]")
ax_ratio.set_ylabel("FSI / noFSI")
ax_ratio.set_xlim(-1000, 1000)
ax_ratio.set_ylim(0, 5)
ax_ratio.legend(fontsize=8, loc="upper left")

plt.savefig("/tmp/compare_oldnew_DUNE_numu.pdf")
plt.savefig("/tmp/compare_oldnew_DUNE_numu.png", dpi=150)
print("saved /tmp/compare_oldnew_DUNE_numu.{pdf,png}")
